/*reqToServer.js*/
export const REQ_TO_SERVER_START = 'REQ_TO_SERVER_START'
export const REQ_TO_SERVER_SUCCESS = 'REQ_TO_SERVER_SUCCESS'
export const REQ_TO_SERVER_FAIL = 'REQ_TO_SERVER_FAIL'
/*auth.js*/
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const LOGOUT = 'LOGOUT'
/*shoppingCart.js*/
// export const SEARCH_INPUT = 'SEARCH_INPUT'
// export const ITEM_CLICKED = 'ITEM_CLICKED'
// export const AMOUNT_INPUT = 'AMOUNT_INPUT'
// export const ADD_TO_CART = 'ADD_TO_CART'
// export const SET_ITEMS = 'SET_ITEMS'
export const SAVE_LOCATION = 'SAVE_LOCATION'
export const FETCH_BRUNCHES_SUCCESS = 'FETCH_BRUNCHES_SUCCESS'
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS'
export const ADD_ITEM_TO_CART_SUCCESS = 'ADD_ITEM_TO_CART_SUCCESS'
export const FETCH_CART_PRODUCTS_SUCCESS = 'FETCH_CART_PRODUCTS_SUCCESS'
export const DELETE_ITEM_FROM_CART_SUCCESS = 'DELETE_ITEM_FROM_CART_SUCCESS'







